export const listaFrutas = ()  =>{
    const frutas = [
        {
            "titulo":"Piña",
            "precio":3000
        },
        {
            "titulo":"Pomelo",
            "precio":2000
        },
        {
            "titulo":"Pera",
            "precio":2400
        },
        {
            "titulo":"Mango",
            "precio":4000
        },
        {
            "titulo":"Coco",
            "precio":2500
        },
        {
            "titulo":"Manzana",
            "precio":2500
        },
        {
            "titulo":"Mora",
            "precio":5300
        },
        {
            "titulo":"Mispero",
            "precio":3000
        },
        {
            "titulo":"Fresa",
            "precio":6000
        },
        {
            "titulo":"Cereza",
            "precio":2600
        },
        {
            "titulo":"Limon",
            "precio":2700
        },
        {
            "titulo":"Melon",
            "precio":1400
        },
        {
            "titulo":"Tamarindo",
            "precio":2190
        },
        {
            "titulo":"Granda",
            "precio":7200
        },
    ]
    return frutas
}