export const listaVerduras = ()  =>{
    const verduras = [
        {
            "id":"v1",
            "img":"https://primicia.com.ve/wp-content/uploads/2020/09/zanahoria-1280x720-1.jpg",
            "titulo":"Zanahoria",
            "precio":3000,
            "descripcion":""
        },
        {
            "id":"v2",
            "img":"https://s1.abcstatics.com/media/bienestar/2019/07/22/brocoli-beneficios-3-kk7H--1248x698@abc.jpg",
            "titulo":"Brócoli",
            "precio":2000,
            "descripcion":""
        },
        {
            "id":"v3",
            "img":"https://dam.cocinafacil.com.mx/wp-content/uploads/2018/04/espinaca.jpg",
            "titulo":"Espinaca",
            "precio":2400,
            "descripcion":""
        },
        {
            "id":"v4",
            "img":"https://encolombia.com/wp-content/uploads/2022/02/Cultivo-de-Pimiento.jpg",
            "titulo":"Pimiento",
            "precio":4000,
            "descripcion":""
        },
        {
            "id":"v5",
            "img":"https://static4.abc.es/media/bienestar/2020/09/09/calabacin-ksKC--1024x512@abc.jpg",
            "titulo":"Clabacín",
            "precio":2500,
            "descripcion":""
        },
        {
            "id":"v6",
            "img":"https://i.blogs.es/77acf0/berenen/1366_2000.jpg",
            "titulo":"Berenjena",
            "precio":2500,
            "descripcion":""
        }
    ]
    return verduras
}